import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { SunIcon, MoonIcon } from "@radix-ui/react-icons";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ThemeSwitch } from "@/components/layout/theme-switch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeSwitch />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
