version: "3.5"

services:
  minecraft-server:
    image: minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
    volumes: 
     - ./data:/minecraft